### ISSUE TITLE
需修正之处

### ISSUE THREAD

**Issue by philipxyc** [ShanghaitechGeekPie/oj-frontend#11]
# 1. 系统所有的的左侧边导航按钮希望统一一下宽度：
![90_SB Z21HY0KQZN2IW%K5D](https://user-images.githubusercontent.com/12481493/63331268-e9055780-c367-11e9-8f27-49586c2b2006.png)

# 2. 【高】instructor页面左侧边的按钮的四方块还没删掉：
![3F9ZO(OE{25YTMYD$UR}D2E](https://user-images.githubusercontent.com/12481493/63331312-020e0880-c368-11e9-8868-f53eb7cd0d32.png)

# 3. 【中】change profile/profile页面里面的字段也包上了按钮的这个样式，看起来会有点误导用户去点。可以换个样式
![MO GKO XA23MVV30AEZ9T$B](https://user-images.githubusercontent.com/12481493/63331346-16520580-c368-11e9-844a-dae55140f7b5.png)

# 4.【中】现在change profile/profile是两个页面，因为rsa公钥是只可改的字段。建议还是做成一个profile页面，然后在页面上可以选择修改。
![~95HBZ{L)E~XQS J CQNIEI](https://user-images.githubusercontent.com/12481493/63331356-1e11aa00-c368-11e9-9625-d9baa2cb88c5.png)

# 5. Submission History页面的delta应该像scoreboard一样用上下三角和颜色做渲染。
![image](https://user-images.githubusercontent.com/12481493/63331456-50230c00-c368-11e9-812a-2dda322dbba2.png)

# 6. 学生端的scoreboard将加入总提交数的字段，教师端的scoreboard还将能看到学生学号等信息。具体接口细节将在接下来的issue讨论

**Comment by LEAFERx** [comment]
1 fixed in #10

**Comment by nekowink** [comment]
> 1 fixed in #10

Nice! Thank you for your contribution :P

**Comment by nekowink** [comment]
Has set up the local debugging environment (with data mocking, [Artanic30/SISTOJ](https://github.com/Artanic30/SISTOJ)). 
Fix of 2, 3 and 5 would be completed soon.

**Comment by nekowink** [comment]
It seems like there is no extra icon beside the nav buttons in Aside /instr (when I am debugging on the dev server).
2 and 3 fixed. The coherent render of Delta field is implemented by adding a new component `ScoreDelta` at /public.

**Comment by llk89** [comment]
#10 didn't fix every button, or more specifically buttons within scoreboard (both in student version and instructor version).
